baseurl: "https://wesleych3n.github.io/"
title: "My Blog"
languageCode: "en-us"
theme:
  - hugo-notice
  - PaperMod
paginate: 10
enableEmoji: true

params:
  env: production
  keywords: [Blog, Portfolio, PaperMod]
  author: Wesley Chen

  defaultTheme: auto # dark, light
  DateFormat: "January 2, 2006"
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  profileMode:
    enabled: true
    title: Wesley Chen
    subtitle: "Software engineer, Machine Vision, Machine Learning"
    imageUrl: "img/bio-photo.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Portrait
    # buttons:
    #   - name: About
    #     url: about
    #   - name: Posts
    #     url: posts
  socialIcons:
    - name: github
      url: "https://github.com/WesleyCh3n"
    - name: linkedin
      url: "https://www.linkedin.com/in/wesleych3n"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/16102997/wesleych3n"
  assets:
    disableHLJS: false

languages:
  en:
    title: "WesleyCh3n"
    subtitle: "Blog"
    readOtherPosts: "Read other posts"

menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts"
    - identifier: "about"
      name: "About"
      url: "/about"
    - identifier: "search"
      name: "Search"
      url: "/search"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

markup:
  highlight:
    style: gruvbox
    lineNos: true
    codeFences: true
    guessSyntax: true
    tabWidth: 2
    lineNumbersInTable: true
